kind: Job
apiVersion: batch/v1
metadata:
  name: myjob
spec:
  parallelism: 5
  template:
    metadata: 
      name: testjob
    spec:
      containers:
      - name: mycont
        image: centos
        command: ["/bin/bash", "-c", "echo Saidemy; sleep 15"]
      restartPolicy: Never
